<a href="https://colab.research.google.com/github/RownakDiganta/Pytorch_Tutorial-/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# LISTS

In [2]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [3]:
my_list_1 = [[1,2,3,4,5],[6,7,8,9,10]]
my_list_1

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAYS

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.50416506, 0.57568302, 0.92879371, 0.22119029],
       [0.91435732, 0.07294108, 0.67712896, 0.59896489],
       [0.98817941, 0.04802052, 0.34735419, 0.81045376]])

In [6]:
np1.dtype

dtype('float64')

# TENSOR

In [11]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.3648, -0.9543, -0.2421, -0.6273],
        [-0.5447,  1.1659, -0.7263, -0.7597],
        [-0.0214,  1.6615, -1.0338, -0.1017]])

In [12]:
tensor_2d.dtype

torch.float32

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
# create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5042, 0.5757, 0.9288, 0.2212],
        [0.9144, 0.0729, 0.6771, 0.5990],
        [0.9882, 0.0480, 0.3474, 0.8105]], dtype=torch.float64)